### ISSUE TITLE
is there a way to catch also hash links?

### ISSUE THREAD

**Issue by zivl** [tcort/markdown-link-check#98] opened 2020-07-13 12:24 UTC
For example, my `README.md` file contains the following link:
```
[example](http://www.example.com/somePage#someNotExistPageSection)
```
The `http` protocol fetched the address and gets `200:OK` but the section is not there anymore...
now...  I know this is how HTTP/browsers work - but is there a way to catch those use cases?

**Comment by NicolasMassart** [comment] 2020-09-25 15:38
The difficulty is to know what to test. For some pages the # anchor is in the HTML directly but for others it's compiled from some JS and requires the page to be rendered. Does having the basic case of looking for the anchor in html source code enough for you or do you absolutely need to look deeper and render the page as if it was displayed on a browser?

**Comment by NicolasMassart** [comment] 2020-09-25 16:02
This may be a duplicate of #91

**Closed** 2020-10-01 14:36 UTC
Labels: duplicate
