### ISSUE TITLE
`3.13.0` (latest) fails to run with `MODULE_NOT_FOUND`

### ISSUE THREAD

**Issue by MikeMcC399** [tcort/markdown-link-check#368] opened 2024-11-05 14:08 UTC
## Current behavior

After updating from `markdown-link-check@3.12.2` to `markdown-link-check@3.13.0` (`latest`), `markdown-link-check` fails to run.

The failure occurs independently of the Node.js version (`v18.20.4`, `v20.18.0`, `v22.11.0` & `v23.1.0`)

## Expected behavior

`markdown-link-check` should run and not fail.

## Steps to reproduce

| Component           | Version       |
| ------------------- | ------------- |
| Ubuntu              | `24.04.1` LTS |
| Node.js             | `22.11.0`     |
| markdown-link-check | `3.13.0`      |

```shell
mkdir markdown-link-check-test
cd markdown-link-check-test
npm init -y
npm install markdown-link-check@latest
touch test.md
npx markdown-link-check test.md
```

## Logs

```text
mike@ubuntu-24:~/github/markdown-link-check-test$ npx markdown-link-check test.md
node:internal/modules/cjs/loader:1249
  const err = new Error(message);
              ^

Error: Cannot find module '/home/mike/github/markdown-link-check-test/reporters/default.js'
Require stack:
- /home/mike/github/markdown-link-check-test/node_modules/markdown-link-check/markdown-link-check
    at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
    at Function._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at getInputs (/home/mike/github/markdown-link-check-test/node_modules/markdown-link-check/markdown-link-check:154:61)
    at main (/home/mike/github/markdown-link-check-test/node_modules/markdown-link-check/markdown-link-check:251:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/mike/github/markdown-link-check-test/node_modules/markdown-link-check/markdown-link-check'
  ]
}

Node.js v22.11.0
````

**Comment by dklimpel** [comment] 2024-11-05 14:10
I can confirm it.

**Comment by dklimpel** [comment] 2024-11-05 14:27
Related to?
- #364

**Comment by MikeMcC399** [comment] 2024-11-05 14:49
7f524dd

https://github.com/tcort/markdown-link-check/blob/c1ca441d9b096e8b6e217249cd9c17f11f8d2068/markdown-link-check#L154

**Comment by tcort** [comment] 2024-11-05 14:54
I have a fix. Stand by. :)

**Comment by dhpollack** [comment] 2024-11-05 14:58
50 minutes for a fix, what took you so long?  :laughing: :100:

**Comment by dklimpel** [comment] 2024-11-05 15:26
Docker image seems to "work". But every check writes a "junit.xml"

**Comment by tcort** [comment] 2024-11-05 15:33
> Docker image seems to "work". But every check writes a "junit.xml"

I just pushed a fix for that.

**Comment by tcort** [comment] 2024-11-05 15:34
> @tcort
> 
> 13.13.1 also fails for me, but with a slightly different stack trace

Working on a fix.

**Closed** 2024-11-05 15:35 UTC

**Comment by MikeMcC399** [comment] 2024-11-05 15:41
@tcort 

It looks like the npm package `markdown-link-check` does not publish the directory `reporters`

![image](https://github.com/user-attachments/assets/68437315-780a-4afc-b3ee-f5d58a0c980e)

**Comment by tcort** [comment] 2024-11-05 16:09
I've never encountered this sort of thing before, and I've been using node.js since 2014. I just did a quick fix to include the reporters in `markdown-link-check`. I'll try to figure out what went wrong later.
