### ISSUE TITLE
how to check links from a local markdown folder (recursive) exclude some specific folder?

### ISSUE THREAD

**Issue by allencloud** [tcort/markdown-link-check#66] opened 2018-11-11 11:20 UTC
Hi, All, 

I am attempting to use markdown-link-check to check links in markdown files of a golang project, which has a vendor folder to vendor others' packages. For example, I do not want to check markdown files in https://github.com/alibaba/pouch/tree/master/vendor.

While I found that I have some issue in checking links exclude the folder `vendor`.

How to construct the command to check links in markdown files, but exclude some specific folders?

Thanks.

Allen Sun

**Comment by nschonni** [comment] 2018-11-11 20:13
Probably a duplicate of #40

**Comment by Peritract** [comment] 2019-01-12 18:48
`find . -path ./vendor -prune -o -name \*.md -exec markdown-link-check {} \;` should exclude all files in the /vendor folder.

**Comment by NicolasMassart** [comment] 2020-09-26 09:09
As showed by @Peritract using exclusion mechanism provided by `find` is the way to solve this one.
Later we may have globs like requested in #40

**Closed by NicolasMassart** 2020-09-26 09:09 UTC
Labels: wontfix
