### ISSUE TITLE
Normalize urls

### ISSUE THREAD

**Issue by cktang88** [tcort/markdown-link-check#100] opened 2020-08-10 22:26 UTC
urls like `blockchain.global/blockchain-innovation` and `unchainedpodcast.co` return 400 status code, even though they're legitimate websites that you can visit in the browser, which seems to be a false negative?

I think using https://www.npmjs.com/package/normalize-url would solve this

**Comment by NicolasMassart** [comment] 2020-09-25 15:50
I'm not sure to understand, do you mean the links are only `blockchain.global/blockchain-innovation` and not providing the scheme like `http://blockchain.global/blockchain-innovation`?
I tried to pass `http://blockchain.global/blockchain-innovation` in markdown-link-checker tests and it succeeds with a 200 code. However, as expected `blockchain.global/blockchain-innovation` only return `TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string.`
I dont have a 400 (bad request).

Could you try to provide a command line or the piece of code that you use to get this result please?

**Comment by NicolasMassart** [comment] 2020-10-02 09:16
Labeled as invalid until we have more detail. Thanks.

**Comment by NicolasMassart** [comment] 2020-11-09 10:02
closing because not reproduced and no answer

**Closed by NicolasMassart** 2020-11-09 10:02 UTC
