### ISSUE TITLE
V3.13.6 completely different and break CI/CD

### ISSUE THREAD

**Issue by LegendSebastianoL** [tcort/markdown-link-check#379] opened 2024-11-30 11:32 UTC
Since I upgraded to V3.13.6 (from 3.12.2), the CI/CD has been completely broken, even though it seems to work perfectly locally on my MAC OS X.

I use this script both in the GitHub workflow and locally:
```
"check:markdown-links": "find docs -type f -name '*.md' | xargs -P0 -L1 npx markdown-link-check"
```

this is the result with 3.13

<img width="553" alt="391232719-3d10dd80-5827-49f1-be51-8aee9691db25" src="https://github.com/user-attachments/assets/5811c562-31a5-41ec-a345-d09cb7e0cc67">

---

and this is how it should be, screenshot of the V3.12.2

<img width="464" alt="Screenshot 2024-11-30 at 12 29 53" src="https://github.com/user-attachments/assets/31346f12-eee9-4dd2-8e96-5d3d248a7d5c">

**Comment by per1234** [comment] 2024-12-04 22:41
@LegendSebastianoL are you using [a markdown-link-check configuration file](https://github.com/tcort/markdown-link-check#config-file-format)?

If so, please close the issue as this is a duplicate of https://github.com/tcort/markdown-link-check/issues/369.

**Closed** 2024-12-05 07:58 UTC
