### ISSUE TITLE
ERR_INVALID_ARG_TYPE when run in docker

### ISSUE THREAD

**Issue by mneverov** [tcort/markdown-link-check#115] opened 2020-09-30 18:46 UTC
Hi,
I followed instructions from the readme:

```
docker build --tag markdown-link-check .
docker run --rm -i markdown-link-check < README.md
```

and got 

```
internal/fs/utils.js:612
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.stat (fs.js:1014:10)
    at Command.<anonymous> (/src/markdown-link-check:65:12)
    at Command.listener [as _actionHandler] (/src/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/src/node_modules/commander/index.js:1002:14)
    at Command.parse (/src/node_modules/commander/index.js:801:10)
    at Object.<anonymous> (/src/markdown-link-check:75:4)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

when run against readme file in this project. The docker build log is attached.
[log.txt](https://github.com/tcort/markdown-link-check/files/5307635/log.txt)

**Comment by NicolasMassart** [comment] 2020-09-30 23:47
This is a duplicate of #67

**Closed by NicolasMassart** 2020-09-30 23:47 UTC
