### ISSUE TITLE
Call markdown-link-check with a list of files

### ISSUE THREAD

**Issue by nvuillam** [tcort/markdown-link-check#150] opened 2021-01-07 17:30 UTC
I would be nice (and improve [Mega-Linter performances](https://nvuillam.github.io/mega-linter/descriptors/markdown_markdown_link_check/) regarding markdown-link-check) if the CLI could take a list of files as parameter

Today, we can call  `markdown-link-check "./README.md"` , as described in the [documentation](https://github.com/tcort/markdown-link-check#check-links-from-a-local-markdown-file)

With such evolution, we could call `markdown-link-check "./README.md" "./CHANGELOG.md" "./docs/index.md" ".docs/other.md"`

**Comment by NicolasMassart** [comment] 2021-01-07 17:58
This is a duplicate of #78

**Closed by NicolasMassart** 2021-01-07 17:58 UTC

**Comment by nvuillam** [comment] 2021-01-07 18:36
oops sorry :)
