### ISSUE TITLE
It should handle directories by default

### ISSUE THREAD

**Issue by gaurav-nelson** [tcort/markdown-link-check#56] opened 2018-07-20 02:05 UTC
At present, it requires us to manually run it on directories using the command
`find . -name \*.md -exec markdown-link-check {} \;`

I believe this should be handled automatically. So that when user runs it on a directory, it should check all markdown files recursively by default.
```
$ markdown-link-check -p run/on/dir
```

Let me know if this is required? I can put together up a PR to address this.

**Comment by nschonni** [comment] 2018-07-20 02:30
Duplicate of #40 I think

**Comment by NicolasMassart** [comment] 2020-09-26 09:20
duplicates #40

**Closed by NicolasMassart** 2020-09-26 09:20 UTC
Labels: duplicate
