### ISSUE TITLE
Parse HTML in order to find anchors (like `#tomato`) in the same document

### ISSUE THREAD

**Issue by sschuberth** [tcort/markdown-link-check#195] opened 2022-04-19 11:22 UTC
`markdown-link-check` doesn't parse HTML, so it can't find `#tomato` in your test, but it is something I'm planning on adding.

_Originally posted by @tcort in https://github.com/tcort/markdown-link-check/issues/193#issuecomment-1076250098_

**Comment by MikeMcC399** [comment] 2022-06-13 11:21
This would be nice to have back again. It used to work in 3.8.7 and no longer works in 3.9.3 or 3.10.2.

**Comment by Shocktrooper** [comment] 2022-11-04 17:20
Hello! Was curious about the status of this because anchor links are valid markdown but they are all currently broken when checking if links are valid

**Comment by MikeMcC399** [comment] 2022-11-04 18:57
@Shocktrooper 
This issue is about anchor links defined in HTML. Is that the same issue that you have?

## Steps to reproduce failure

`195.md` file contains:
```
- [Open Issues](#issue_list) 
<a name='issue_list'>Open Issues</a>
```

```
npm install markdown-link-check@3.8.7
npx markdown-link-check ./195.md

FILE: ./195.md
[✓] #issue_list

1 links checked.
```

Now update to latest version:

```
npm install markdown-link-check@3.10.3
npx markdown-link-check ./195.md

FILE: ./195.md
  [✖] #issue_list

  1 links checked.

  ERROR: 1 dead links found!
  [✖] #issue_list → Status: 404
```

## Steps to reproduce correct checking of anchor links

If the anchor link is defined through Markdown (no use of HTML in Markdown file), then the check works:

```
[link to issues](#issues)
# issues
```
```
FILE: ./195-b.md
  [✓] #issues

  1 links checked.
```

**Comment by Shocktrooper** [comment] 2022-11-04 19:48
Oh my apologies my issue is plain anchor links in markdown. Not html

**Comment by MikeMcC399** [comment] 2022-11-04 20:16
@Shocktrooper 
> ... my issue is plain anchor links in markdown. Not html

Perhaps you could give an example of a failing test? Also which version of `markdown-link-check` are you using? Does my example give an error or does it work for you?

```
[link to issues](#issue-list)
# issue list
```

**Comment by MikeMcC399** [comment] 2022-12-08 20:11
I am still stuck with using "markdown-link-check": "~3.8.7" due to this regression. Is there any chance of getting it fixed in 3.10.* or later?

**Comment by Shocktrooper** [comment] 2022-12-13 16:14
@MikeMcC399 It appears that I had an issue with my syntax that was not apparent and it is not an issue with the tool

**Comment by srl295** [comment] 2022-12-13 21:27
@Shocktrooper would you be able to give an example of what the syntax issue was and how it was fixed? just in case that's what i or others are running into.

**Comment by Shocktrooper** [comment] 2022-12-14 04:01
for `## Architecture-Diagram`

`[Architecture Diagram](#_Architecture_Diagram)`
was changed to
`[Architecture Diagram](#architecture-diagram)`

and for ``## Access and authentication``

`[Authentication](#_Authentication)`
was changed to
`[Authentication](#access-and-authentication)`

The first example was an old and valid way that anchor links worked in an older version of markdown and the second example was just a rename someone forgot I believe

**Comment by jhvhs** [comment] 2023-02-21 13:15
@MikeMcC399 Sorry to revive an old conversation, but just to be clear, versions 3.8 and prior reported "success" on internal anchor links, but the fact is, it was an unproven positive. Try to change the fragment to any gibberish, and it will pass with flying colours. The solution I see at the moment, until the issue is fixed, is to ignore URLs that consist entirely of fragments. This way they will remain explicitly unchecked, showing up in the report as ignored.

**Comment by MikeMcC399** [comment] 2023-02-21 15:19
@jhvhs 
No need to apologize for responding to an open issue, however old it is!

Shockingly you are correct! 

A bad anchor link is not detected in 3.8.7. All pass.

An anchor link which is not embedded in HTML passes in 3.10.3. - correct
An anchor link which is embedded in HTML fails in 3.10.3. - subject of this issue. Would expect to pass but it fails.
An anchor link to a non existent target fails in 3.10.3 - correct

Tested with:

```markdown
- [Good regular link](#link1)
- [Good link in HTML](#link2)
- [Bad link](#link3)
# link1
<a name='link2'>Link 2</a>
```

**Comment by adoyle-h** [comment] 2023-02-24 03:07
You can try https://github.com/lycheeverse/lychee

**Comment by MikeMcC399** [comment] 2023-03-02 15:31
@tcort 

Do you have any comments on this thread?

**Comment by yusufsheiqh** [comment] 2023-09-21 14:05
Has there been any progress on this issue?

**Comment by dklimpel** [comment] 2024-06-03 11:13
I have created a PR to solve the issue.
- #331

Rreviews or suggestions for improvement are welcome.

**Comment by MikeMcC399** [comment] 2024-11-05 17:48
- It looks like this issue is resolved, since https://github.com/tcort/markdown-link-check/pull/331 is now merged.

**Closed** 2024-11-05 18:19 UTC
