### ISSUE TITLE
DeprecationWarning: The `punycode` module is deprecated...with Docker

### ISSUE THREAD

**Issue by valorisa** [tcort/markdown-link-check#314] opened 2024-04-12 16:27 UTC
Hello,

By using Docker from macOS Sonoma, I obtain the following message :

```
% docker run --rm --name markdown-link-check --platform linux/amd64 -v ${PWD}:/Projets/markdownlint/:ro -i ghcr.io/tcort/markdown-link-check:3.12.1 CONTRIBUTING.md README.md
(node:1) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

FILE: CONTRIBUTING.md
  No hyperlinks found!

  0 links checked.

FILE: README.md
  [✓] https://www.npmjs.com/package/isemail
  [✓] https://github.com/gaurav-nelson/github-action-markdown-link-check
  [✓] https://pre-commit.com
  [✓] https://megalinter.io/latest/
  [✓] https://megalinter.io/latest/descriptors/markdown_markdown_link_check/
  [✓] https://www.npmjs.com/package/ms
  [✓] https://github.com/tcort/markdown-link-check/issues/78
  [✓] https://github.com/tcort/markdown-link-check/blob/master/LICENSE.md
  [✓] https://github.com/tcort/markdown-link-check/workflows/Test%20library/badge.svg

  9 links checked.
```

I use Portainer from Docker Desktop and I would like to know how to downgrade NODE_VERSION
21.7.1 to 20.12.2 and Yarn version 1.22.19 to 4.1.1. Is it possible to proceed by changing this via Dockerfile or others files, or other way ? Thanks a lot.

<img width="930" alt="Capture d’écran 2024-04-12 à 17 33 14" src="https://github.com/tcort/markdown-link-check/assets/13067566/667103a5-0ca6-48c3-9a7a-f20c4e1001c0">

**Comment by MikeMcC399** [comment] 2024-05-20 12:48
@valorisa 

- You have hit the resolved issue https://github.com/yarnpkg/yarn/issues/9013 which is not related to `markdown-link-check`. You may be able to resolve it in your environment by using a different Docker image.

**Comment by dklimpel** [comment] 2024-06-02 09:18
@MikeMcC399 Do you have a hint for a better image?

At the moment it is:

https://github.com/tcort/markdown-link-check/blob/71ccb4129a1fa86f6904f35c1b26348dfce1438d/Dockerfile#L1#

It is currently: sha: 3687802f25d2da52901b6a30d9bfaed81234b2ec63e52c01fbd1fc176fdbabbb
- [22.2.0-alpine3.20](https://hub.docker.com/layers/library/node/22.2.0-alpine3.20/images/sha256-3687802f25d2da52901b6a30d9bfaed81234b2ec63e52c01fbd1fc176fdbabbb?context=explore)
- [alpine](https://hub.docker.com/layers/library/node/alpine/images/sha256-3687802f25d2da52901b6a30d9bfaed81234b2ec63e52c01fbd1fc176fdbabbb?context=explore)

**Comment by MikeMcC399** [comment] 2024-06-02 10:00
@dklimpel 

[node:lts-alpine](https://hub.docker.com/layers/library/node/lts-alpine/images/sha256-389ae25ab30b4739d863c6116a686901ae99e9ccaaed524a0db9481531266f82?context=explore) has Yarn `1.22.22` integrated

I guess that `node:alpine` (`node:alpine:latest`) & `node:22.x-alpine3.x` will catch up soon, however currently they are still on Yarn `1.22.19`.

Since this is only a deprecation warning, you may just prefer to wait.

**Comment by MikeMcC399** [comment] 2024-10-18 07:54
- related issue in https://github.com/tcort/markdown-link-check/issues/365

**Comment by MikeMcC399** [comment] 2024-10-18 08:23
It seems that there are two potential sources of the `punycode` deprecation warning in the Docker image:

- Yarn not being updated to `1.22.22`
- Node.js `21.x` or later being used.

I looked at the `latest` image, also tagged as

- `stable`
- `3.12.2`
- `3.12`
- `3`

```shell
docker run -it --rm --entrypoint sh ghcr.io/tcort/markdown-link-check:stable
```

and found that this is still the case

```text
/src # node -v
v22.2.0
/src # yarn -v
1.22.19
/src #
```

**Comment by MikeMcC399** [comment] 2024-10-18 14:50
@valorisa 

I looked at this again, and the main source of the deprecation warning is the now unsupported [isemmail](https://github.com/skeggse/isemail) .

Although potentially the old version of Yarn could cause a deprecation warning, if you are using the Docker image according to the instructions in [README > Run using Docker](https://github.com/tcort/markdown-link-check/blob/master/README.md#run-using-docker), then you are not using Yarn to run `markdown-link-check`. It is run directly through `node`.

```shell
docker run -v ${PWD}:/tmp:ro --rm -i ghcr.io/tcort/markdown-link-check:stable /tmp/README.md
```

- Sorry once again for the misinterpretation! I hope that https://github.com/tcort/markdown-link-check/issues/365 explains it better and points to the real root cause.

BTW: I checked the current `node:alpine` Docker image and this has now caught up with the Yarn `1.22.22` version, so the next time that the `markdown-link-check` Docker image is built, it will have the latest Yarn Classic v1 version installed.

**Comment by valorisa** [comment] 2024-10-18 14:53
Hello Mike,
I will take a look at this issue again.

**Comment by valorisa** [comment] 2024-10-18 17:57
![Capture d’écran 2024-10-18 à 19 55 48](https://github.com/user-attachments/assets/0783d0e1-8bfa-4bd7-b1b1-9ca1aad97643)

**Comment by valorisa** [comment] 2024-10-18 17:59
```
darkfairie@iMac-de-Isabelle /tmp % node -v
v22.9.0
darkfairie@iMac-de-Isabelle /tmp % 
darkfairie@iMac-de-Isabelle /tmp % 
darkfairie@iMac-de-Isabelle /tmp % 
darkfairie@iMac-de-Isabelle /tmp % yarn -v
zsh: command not found: yarn
darkfairie@iMac-de-Isabelle /tmp % 
```

**Comment by MikeMcC399** [comment] 2024-11-07 09:34
@valorisa 

It seems this issue is now resolved with the new `stable` Docker version - equivalent to` ghcr.io/tcort/markdown-link-check:3.13.6`. Would you like to check?

## Test steps

```shell
git clone https://github.com/tcort/markdown-link-check
cd markdown-link-check
docker run --rm --entrypoint sh ghcr.io/tcort/markdown-link-check:stable -c 'node -v'
docker run -v ${PWD}:/tmp:ro --rm -i ghcr.io/tcort/markdown-link-check:stable /tmp/README.md
```

## Test results

Docker containers listed under https://github.com/tcort/markdown-link-check/pkgs/container/markdown-link-check

Replace `stable` above with numerical version e.g. `3.13.6`

Running Docker in a virtual Ubuntu `24.04.1` LTS runner

| `ghcr.io/tcort/markdown-link-check` tag | Node.js   | in Result                     |
| --------------------------------------- | --------- | ----------------------------- |
| `3.12.2`                                | `v22.2.0` | [DEP0040] DeprecationWarning: |
| `3.13.6`                                | `v23.1.0` | no DeprecationWarning         |

**Comment by valorisa** [comment] 2024-11-07 09:37
Thanks for the information.

**Comment by valorisa** [comment] 2024-11-08 21:05
```
darkfairie@iMac-de-Isabelle Projets % git clone https://github.com/tcort/markdown-link-check
Clonage dans 'markdown-link-check'...
remote: Enumerating objects: 1656, done.
remote: Counting objects: 100% (1061/1061), done.
remote: Compressing objects: 100% (293/293), done.
remote: Total 1656 (delta 807), reused 946 (delta 762), pack-reused 595 (from 1
Réception d'objets: 100% (1656/1656), 617.86 Kio | 2.73 Mio/s, fait.
Résolution des deltas: 100% (1008/1008), fait.
darkfairie@iMac-de-Isabelle Projets % 
darkfairie@iMac-de-Isabelle Projets % 
darkfairie@iMac-de-Isabelle Projets % 
darkfairie@iMac-de-Isabelle Projets % cd markdown-link-check
darkfairie@iMac-de-Isabelle markdown-link-check % docker run --rm --entrypoint sh ghcr.io/tcort/markdown-link-check:stable -c 'node -v'
v23.1.0
darkfairie@iMac-de-Isabelle markdown-link-check % docker run -v ${PWD}:/tmp:ro --rm -i ghcr.io/tcort/markdown-link-check:stable /tmp/README.md

FILE: /tmp/README.md
  [✓] https://www.npmjs.com/package/isemail
  [✓] https://github.com/gaurav-nelson/github-action-markdown-link-check
  [✓] https://pre-commit.com
  [✓] https://megalinter.io/latest/
  [✓] https://megalinter.io/latest/descriptors/markdown_markdown_link_check/
  [✓] https://www.npmjs.com/package/ms
  [✓] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_the_replacement
  [✓] https://github.com/tcort/markdown-link-check/blob/master/LICENSE.md
  [✓] https://github.com/tcort/markdown-link-check/actions/workflows/ci.yml/badge.svg

  9 links checked.
darkfairie@iMac-de-Isabelle markdown-link-check % 
```

**Comment by valorisa** [comment] 2024-11-08 22:18
```
darkfairie@iMac-de-Isabelle ~ % npm install -g markdown-link-check

added 10 packages, removed 3 packages, and changed 67 packages in 23s

18 packages are looking for funding
  run `npm fund` for details
darkfairie@iMac-de-Isabelle ~ % cd Projets/markdown-link-check 
darkfairie@iMac-de-Isabelle markdown-link-check % ls
CHANGELOG.md		README.md		package-lock.json
CONTRIBUTING.md		eslint.config.mjs	package.json
Dockerfile		index.js		test
LICENSE.md		markdown-link-check
darkfairie@iMac-de-Isabelle markdown-link-check % markdown-link-check ./README.md

FILE: ./README.md
  [✓] https://www.npmjs.com/package/isemail
  [✓] https://github.com/gaurav-nelson/github-action-markdown-link-check
  [✓] https://pre-commit.com
  [✓] https://megalinter.io/latest/
  [✓] https://megalinter.io/latest/descriptors/markdown_markdown_link_check/
  [✓] https://www.npmjs.com/package/ms
  [✓] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_the_replacement
  [✓] https://github.com/tcort/markdown-link-check/blob/master/LICENSE.md
  [✓] https://github.com/tcort/markdown-link-check/actions/workflows/ci.yml/badge.svg

  9 links checked.
darkfairie@iMac-de-Isabelle markdown-link-check %
```

**Comment by MikeMcC399** [comment] 2024-11-15 17:57
@valorisa 

If this issue is resolved for you, you should be able to close it with the button ⬇️ below.

**Closed** 2024-11-15 18:15 UTC
